services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
    environment:
      - POSTGRES_SERVER=postgres
      - MONGODB_URL=mongodb://mongodb:27017/sentinelprobe
      - REDIS_HOST=redis
      - DEBUG=true
    restart: on-failure
    command: >
      sh -c "while ! nc -z postgres 5432; do
        echo 'Waiting for postgres...'
        sleep 1
      done &&
      while ! nc -z mongodb 27017; do
        echo 'Waiting for mongodb...'
        sleep 1
      done &&
      while ! nc -z redis 6379; do
        echo 'Waiting for redis...'
        sleep 1
      done &&
      python -m sentinelprobe migrate && python -m sentinelprobe run"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sentinelprobe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
