site_name: SentinelProbe Documentation
site_description: Documentation for the SentinelProbe AI-powered penetration testing system
site_author: SentinelProbe Team
repo_url: https://github.com/yourusername/sentinelprobe
repo_name: sentinelprobe

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - def_list
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/sentinelprobe
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sentinelprobe

nav:
  - Home: wiki/index.md
  - Getting Started:
      - Installation: wiki/installation.md
      - Quick Start: wiki/quick-start.md
      - System Requirements: wiki/system-requirements.md
      - Architecture Overview: wiki/architecture-overview.md
  - User Guides:
      - Configuration: wiki/configuration.md
      - Running Your First Scan: wiki/first-scan.md
      - Understanding Reports: wiki/understanding-reports.md
      - Managing Jobs: wiki/managing-jobs.md
  - Component Documentation:
      - Reconnaissance Module: wiki/components/reconnaissance.md
      - AI Decision Engine: wiki/components/ai-decision-engine.md
      - Vulnerability Scanner: wiki/components/vulnerability-scanner.md
      - Exploitation Engine: wiki/components/exploitation-engine.md
      - Post-Exploitation Module: wiki/components/post-exploitation.md
      - Reporting Engine: wiki/components/reporting-engine.md
  - Advanced Usage:
      - Custom Rule Development: wiki/advanced/custom-rules.md
      - Plugin Development: wiki/advanced/plugin-development.md
      - API Reference: wiki/advanced/api-reference.md
      - Integration Guide: wiki/advanced/integration.md
  - Contributing:
      - Development Setup: wiki/contributing/development-setup.md
      - Coding Standards: wiki/contributing/coding-standards.md
      - Testing Guidelines: wiki/contributing/testing.md
      - Pull Request Process: wiki/contributing/pull-requests.md
  - Project Info:
      - Todo List: planning/TODO.md
      - Implementation Plan: planning/implementation_plan.md

docs_dir: docs
